name: Build and Release

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      # Push events on main branch
      - main

jobs:
  build_game:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Checkout repo to remote machine
      - name: Set up OpenJDK13 
        uses: actions/setup-java@v1
        with:
          java-version: '13'

      - name: Build Game
        run: |
          cd $GRADLE_DIR
          chmod +x ./gradlew
          ./gradlew --stacktrace build
          ls -al
        env:
          GRADLE_DIR: 'source' # Modify this to wherever './gradlew' is 

      - name: Automatic Release # note the path for the files on this one
        uses: marvinpinto/action-automatic-releases@v1.1.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest Build of Game"
          files: |
            ./source/desktop/build/libs/*.jar 
        
  
          